name: faker_app_flutter_firebase
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: 1.0.5
  flutter_riverpod: 2.3.10
  go_router: 10.1.1
  equatable: 2.0.5
  firebase_core: ^2.22.0
  firebase_ui_auth: ^1.10.0
  firebase_auth: ^4.14.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 2.0.2

flutter:
  uses-material-design: true
